language: ruby
cache: bundler

rvm:
  - 1.9.3
  - jruby-19mode

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - catherine@sportsdatallc.com
    on_failure: change
    on_success: never